version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker
    command: celery -A propostas_emprestimo worker --loglevel=info
    depends_on:
      - rabbitmq

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "sleep 15 && python manage.py runserver 0.0.0.0:8000 --settings=propostas_emprestimo.settings"
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    depends_on:
      - celery-worker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
